version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    command: ["node", "server.js"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
